"use strict";

/**
 * Keep in sync with lib/render/designArtboardSpec.ts
 */
const DESIGN_ARTBOARD_WIDTH_PX = 2400;
const DESIGN_ARTBOARD_HEIGHT_PX = 1500;
const DESIGN_ARTBOARD_ASPECT_RATIO = DESIGN_ARTBOARD_WIDTH_PX / DESIGN_ARTBOARD_HEIGHT_PX;
const DEFAULT_GARMENT_SAFE_AREA = { x: 0.14, y: 0.275, w: 0.72, h: 0.45 };

module.exports = {
  DESIGN_ARTBOARD_WIDTH_PX,
  DESIGN_ARTBOARD_HEIGHT_PX,
  DESIGN_ARTBOARD_ASPECT_RATIO,
  DEFAULT_GARMENT_SAFE_AREA,
};
